@review = http://127.0.0.1:6969/api/v1/reviews
@users = http://127.0.0.1:6969/api/v1/users

@tours = http://127.0.0.1:6969/api/v1/tours

### Get All reviews
GET {{review}}

#======================LOGIN======================#
### Login and get data
# @name acc1
POST {{users}}/login HTTP/1.1
content-type: application/json

{
  "email": "long123@gmail.com",
  "password":"12345678905"
}
###
@tokenAcc1 = {{acc1.response.body.token}}

#======================ACTION AFTER AUTHENTICATION======================#

### Set Token
# @token = {{tokenAcc1}}
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVjOGExZDViMDE5MGIyMTQzNjBkYzA1NyIsImlhdCI6MTU5MDA0NTU1MywiZXhwIjoxNTkyNjM3NTUzfQ.UW9DnlKPVHYJn2ShMh7N9sZJrd8GPjfAx6Hs8tDvV48

#--------------------------------------------------------------------------#

### Get a review
GET {{review}}/5c8a38da14eb5c17645c911c HTTP/1.1
Authorization: Bearer {{token}}

### Post a review
POST {{review}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

  {
    "review": "Cựu sao Barca mất tất cả vì ham tiền và ăn chơi trác táng 2 GIỜ TRƯỚC THỂ THAO Alex Song từng có thời điểm bỏ túi 15.000 bảng/tuần tại Arsenal. Anh cũng được Barca chiêu mộ sau đó, nhưng tiền vệ này vẫn tay trắng.",
    "rating": 1
  }


### Post a review with tour ID in URL and get an User ID from authentication
POST {{tours}}/5c88fa8cf4afda39709c2951/reviews HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

  {
    "review": "Tìm hiểu thêm về các loại trà Lipton. Thương hiệu với danh mục sản phẩm đa dạng: trà nóng và trà lạnh, trà đen, trà xanh và trà thảo mộc.",
    "rating": 3
  }


### Post a incorrect TourId
POST {{review}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

  {
    "review": "Wrong tour, wrong user",
    "rating": 1,
    "tour": "5c88fa8cf4afda39709c2954",
    "user": "5c88fa8cf4afda39709c2954"
  }

### Get a review of a specific tour
GET {{tours}}/5c88fa8cf4afda39709c2951/reviews

### Get a tour
GET {{tours}}/5c88fa8cf4afda39709c2951 HTTP/1.1
Authorization: Bearer {{token}}

### Delete review - tulanh or leadGuide
DELETE {{review}}/5ec3c7fad87cdb3fa37a9668 HTTP/1.1
Authorization: Bearer {{token}}


###Update Review
PATCH {{review}}/5c8a34ed14eb5c17645c9108
content-type: application/json

{
    "review": "Wrong tour, wrong user",
    "rating": 1
}