@review = http://127.0.0.1:6969/api/v1/reviews
@users = http://127.0.0.1:6969/api/v1/users

@tours = http://127.0.0.1:6969/api/v1/tours



#======================Set Token======================#

### Token tu Lanh
#@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNzIwZjA1ZTdiNzg0Mjk3YTBmYmMwNCIsImlhdCI6MTYwMTQzODQ5MSwiZXhwIjoxNjAyMzAyNDkxfQ.sf4-IrkC3-_YqymfjQDfYP1cUVwMsnHWlL_lw6Zj3kc

# token user 1
# @token = 


# token user 2
 @token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVmNzIxZmIwYTRmNmQ2MzkxZmFlNTEyOSIsImlhdCI6MTYwMTUzMjA4MSwiZXhwIjoxNjAyMzk2MDgxfQ.gmKxRgh2uTPvvQYrrM5qsltA2gLo01t39i13ZgG-A7g


#======================ACTION======================#

### Get All reviews
GET {{review}}

### Get a review
GET {{review}}/5f6d8b6b64fb1c7c487bb799  HTTP/1.1
Authorization: Bearer {{token}}

### Post a review with tour ID in URL and get an User ID from authentication
POST {{tours}}/5f758c3381230163b4475860/reviews HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

  {
    "review": "Tìm hiểu thêm về các loại trà Lipton. Thương hiệu với danh mục sản phẩm đa dạng: trà nóng và trà lạnh, trà đen, trà xanh và trà thảo mộc.",
    "rating": 2
  }

### Get a review of a specific tour
GET {{tours}}/5f758c3381230163b4475860/reviews?sort=-createAt

### Del a tour - check if review also be deleted or not
DELETE {{tours}}/5f7462b2b86dc1797ccf7ea8 HTTP/1.1
Authorization: Bearer {{token}}

### Get a tour
GET {{tours}}/5f7462b2b86dc1797ccf7ea8 HTTP/1.1
Authorization: Bearer {{token}}

### Delete review - admin or review owner
DELETE {{review}}/5f75a420364c156e4b9823f7 HTTP/1.1
Authorization: Bearer {{token}}

#5f75a420364c156e4b9823f7

###Update Review
PATCH {{review}}/5f54c94f964ea41f89ef7e14
content-type: application/json
Authorization: Bearer {{token}}

{
    "review": "Wrong tour, wrong user",
    "rating": 5
}


### ----- ERROR HANDLER ----------

### Post a review - error - Review must belong to a tour!!!
POST {{review}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

  {
    "review": "Cựu sao Barca mất tất cả vì ham tiền và ăn chơi trác táng 2 GIỜ TRƯỚC THỂ THAO Alex Song từng có thời điểm bỏ túi 15.000 bảng/tuần tại Arsenal. Anh cũng được Barca chiêu mộ sau đó, nhưng tiền vệ này vẫn tay trắng.",
    "rating": 1
  }


### Post a incorrect TourId
POST {{review}} HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

  {
    "review": "Wrong tour, wrong user",
    "rating": 1,
    "tour": "5c88fa8cf4afda39709c2954",
    "user": "5c88fa8cf4afda39709c2954"
  }
