

@users = http://127.0.0.1:6969/api/v1/users

### Wrong URL
GET http://127.0.0.1:6969/api/v10/tours

###Wrong URL 2
GET {{users}}/monthly-splan/:2021

### Get all users
GET {{users}} HTTP/1.1

### Get a user
GET {{users}}/5c8a1d5b0190b214360dc057 HTTP/1.1

### Get a 404 user
GET {{users}}/5d99ad17cbc74c33e46d9c60 HTTP/1.1




							
### Update user
PATCH {{users}}/5c8a1dfa2f8fb814b56fa181 HTTP/1.1
content-type: application/json

{
"password": "$2a$12$hP1h2pnNp7wgyZNRwPsOTeZuNzWBv7vHmsR3DT/OaPSUBQT.y0S..",
"passwordConfirm": "$2a$12$hP1h2pnNp7wgyZNRwPsOTeZuNzWBv7vHmsR3DT/OaPSUBQT.y0S.."
}
					

### Delete user
DELETE {{users}}/5dc4ed0a1d4e611e505f9c00 HTTP/1.1
					 