@users = http://127.0.0.1:6969/api/v1/users
@tours = http://127.0.0.1:6969/api/v1/tours


#-------------------------SIGN UP-------------------------#

### Sign up an user
# @name signupAcc3
POST {{users}}/signup HTTP/1.1
content-type: application/json

  {
    "name": "Indonesia",
    "email": "indonesia@gmail.com",
    "password":"tengteng",
    "passwordConfirm":"tengteng"
  }
###  
@tokenAcc3 = {{signupAcc3.response.body.token}}


### Sign up an user
# @name signupAcc2
POST {{users}}/signup HTTP/1.1
content-type: application/json

  {
    "name": " Longo",
    "email": "long123@gmail.com",
    "password":"chienthangthanh",
    "passwordConfirm":"chienthangthanh"
  }

###
@tokenAcc2 = {{signupAcc2.response.body.token}}


#-------------------------LOG IN-------------------------#

### Login and get data
# @name acc1
POST {{users}}/login HTTP/1.1
content-type: application/json

{
  "email": "long123@gmail.com",
  "password":"12345678905"
}

###
@tokenAcc1 = {{acc1.response.body.token}}



### Sign up 'tulanh' user
# @name tulanh1
POST {{users}}/signup HTTP/1.1
content-type: application/json

  {
    "name": "Tuan Long",
    "email": "longtuan@gmail.com",
    "password":"12345678905",
    "passwordConfirm":"12345678905"
  }

### Login tu lanh
# @name tulanh
POST {{users}}/login HTTP/1.1
content-type: application/json

{
  "email": "longtuan@gmail.com",
  "password":"12345678905"
}


### Token tu Lanh
@tokentulanh = {{tulanh.response.body.token}}




#-------------------------FORGET AND RESET PASSWORD-------------------------#

### forgot password
POST {{users}}/forgotPassword HTTP/1.1
content-type: application/json

{
  "email": "longtuan@gmail.com"
}

### reset Password
# @name resetPass
PATCH {{users}}/resetPassword/265e433de9a7c05c6005fc1ad8811f37cc8e90e32177b96f81ec06164d476c70
content-type: application/json

{
  "password":"12345678905",
  "passwordConfirm": "12345678905"
}

### Token reset Pass
@tokenResetPass = {{resetPass.response.body.token}}


#======================ACTION AFTER AUTHENTICATION======================#

### Set Token
@token = {{tokenAcc3}}

#--------------------------------------------------------------------------#

### Get all tour
GET {{tours}} HTTP/1.1
Authorization: Bearer {{token}}

### Get a tour
GET {{tours}}/5d99ad17cbc74c33e46d9c54 HTTP/1.1
Authorization: Bearer {{token}}

### Delete tour - tulanh or leadGuide
DELETE {{tours}}/5d943906721ba4595616e735 HTTP/1.1
Authorization: Bearer {{token}}

### Update tour
PATCH {{tours}}/5d99ad17cbc74c33e46d9c54 HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
	"name": "Ha Long Boi Loi Mua Lu",
  "price": "1999"
}

### Update Password
PATCH {{users}}/updateMyPassword HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "oldPassword":"1234567890555",
  "newPassword":"12345678905",
  "passwordConfirm": "12345678905"
}


### Update Me
PATCH {{users}}/updateMe HTTP/1.1
content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Choi Lon choi bo",
  "active": "true"
}

### Delete User

DELETE {{users}}/deleteMe HTTP/1.1
Authorization: Bearer {{token}}